# Generated by Django 5.0.6 on 2024-06-15 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('client_id', models.CharField(default=None, max_length=255)),
                ('secret', models.CharField(default=None, max_length=255)),
                ('key', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SocialProvider',
                'managed': True,
            },
        ),
    ]
