# Generated by Django 5.0.6 on 2024-05-25 19:29

import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlaguideObject',
            fields=[
                ('ala_object_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'AlaguideObjects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('audiobook_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('audio_file', models.FileField(upload_to=pathlib.PurePosixPath('/Users/raiqasvl/Enterprise/apps_development/alaguide_arc/media/audio'))),
            ],
            options={
                'db_table': 'AudioBooks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'LandmarksCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('cityname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'Cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('countryname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('landmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('landmarkname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_file', models.FileField(upload_to=pathlib.PurePosixPath('/Users/raiqasvl/Enterprise/apps_development/alaguide_arc/media/img'))),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'Landmarks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LandmarkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'LandmarkTags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'MapData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=255)),
                ('secret', models.CharField(max_length=255)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'SocialProvider',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tagname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('default_country_id', models.IntegerField(default=1)),
                ('default_city_id', models.IntegerField(default=1)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LikeRating',
            fields=[
                ('like_rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=5)),
                ('date_liked_or_rated', models.DateField()),
                ('landmark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.landmark')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.accountuser')),
            ],
            options={
                'db_table': 'LikesRatings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('date_posted', models.DateField()),
                ('landmark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.landmark')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.accountuser')),
            ],
            options={
                'db_table': 'UserReviews',
                'managed': True,
            },
        ),
    ]
