# Generated by Django 5.0.6 on 2024-05-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialprovider',
            options={'managed': True},
        ),
    ]
