"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import sys
import os
from pathlib import Path
from server import local_vars

SESSION_ENGINE = "django.contrib.sessions.backends.db"

ADMIN_JS = True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = local_vars.SECRET_KEY
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0"]

CORS_ALLOW_ALL_ORIGINS = True

SITE_ID = 1



# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "whitenoise.runserver_nostatic",
    "django.contrib.sites",
    # SimpleUI
    "simpleui",
    # CORS
    "corsheaders",
    # App - Modules
    "api.apps.ApisConfig",
    "core.apps.CoreConfig",
    # JWT
    "rest_framework",
    "rest_framework.authtoken",
    # AllAuth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.facebook",
    # Templates
    "crispy_forms",
    "crispy_bootstrap4",
    # Google Maps API
    "googlemaps",
]

# Provider specific settings
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "OAUTH_PKCE_ENABLED": True,
    },
    "facebook": {
        "METHOD": "oauth2",  # Set to 'js_sdk' to use the Facebook connect SDK
        #'SDK_URL': '//connect.facebook.net/{locale}/sdk.js',
        "SCOPE": ["email", "public_profile"],
        "AUTH_PARAMS": {"auth_type": "reauthenticate"},
        "INIT_PARAMS": {"cookie": True},
        "FIELDS": [
            "id",
            "first_name",
            "last_name",
            "middle_name",
            "name",
            "name_format",
            "picture",
            "short_name",
        ],
        "EXCHANGE_TOKEN": True,
        #'LOCALE_FUNC': 'path.to.callable',
        "VERIFIED_EMAIL": False,
        "VERSION": "v13.0",
        "GRAPH_API_URL": "https://graph.facebook.com/v13.0",
    },
    "github": {
        "SCOPE": [
            "user",
            "repo",
            "read:org",
        ],
    },
}


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # CORS
    "corsheaders.middleware.CorsMiddleware",
    # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",
]


ROOT_URLCONF = "server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            BASE_DIR / "templates" / "map",  # Your custom template directory
            BASE_DIR / "templates" / "dashboard",  # Your custom template directory
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                # `allauth` needs this from django
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "server.wsgi.application"
ROOT_URLCONF = "server.urls"

# SIMPLE UI
SIMPLEUI_CONFIG = {
    'system_keep': True,  
    'menu_display': ['auth', 'api', 'core', 'server'],  
    'dynamic': True,  
}

SIMPLEUI_HOME_INFO = False  # Отключить домашнюю страницу SimpleUI


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASE_FILE = BASE_DIR / "backend" / "src" / "server" / "database" / "alaguide_db"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": local_vars.MYSQL_NAME,
        "USER": local_vars.MYSQL_USER,
        "PASSWORD": local_vars.MYSQL_PASSWORD,  # Use environment variable
        "HOST": "localhost",
        "PORT": "3306",
    }
}

if "test" in sys.argv:
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.mysql",
        "NAME": local_vars.MYSQL_TEST_NAME,
        "USER": local_vars.MYSQL_USER,
        "PASSWORD": local_vars.MYSQL_PASSWORD,  # Use environment variable
        "HOST": local_vars.MYSQL_HOST,
        "PORT": "3306",
    }

SILENCED_SYSTEM_CHECKS = ["models.W036"]

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CALSSES": [
        "rest_framework.permissions.AllowAny",
    ]
}


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "static" / "admin",
    BASE_DIR / "static" / "assets",
    BASE_DIR / "static" / "images",
    BASE_DIR / "static" / "images" / "landmarks",
    BASE_DIR / "static" / "images" / "socialproviders",
    BASE_DIR / "static" / "rest_framework",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media" 


STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Email File Based Test
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_FILE_PATH = BASE_DIR / "emails"


# AllAuth settings
LOGIN_REDIRECT_URL = "home"

LOGOUT_REDIRECT_URL = "login"

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"

CRISPY_TEMPLATE_PACK = "bootstrap4"

ACCOUNT_LOGOUT_REDIRECT_URL = "account_login"

ACCOUNT_EMAIL_REQUIRED = True

ACCOUNT_LOGOUT_ON_GET = True

#ACCOUNT_EMAIL_VERIFICATION = "mandatory"

ACCOUNT_CONFIRM_EMAIL_ON_GET = False

SOCIALACCOUNT_QUERY_EMAIL = True

ACCOUNT_SESSION_REMEMBER = True

SOCIALACCOUNT_STORE_TOKENS = True

# Other App Configurations
DEFAULT_COUNTRY_ID = 1
DEFAULT_CITY_ID = 1
