// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJIHOR85lIhIADCOYU_gCFtF1p0N_QUPo',
    appId: '1:16607490862:web:afcac6ccfc88ad59e9c0bf',
    messagingSenderId: '16607490862',
    projectId: 'alaguide-app',
    authDomain: 'alaguide-app.firebaseapp.com',
    storageBucket: 'alaguide-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgtapl8p9hPI85UfwgyWmUSRv3c1oDLis',
    appId: '1:16607490862:android:9fecfb111d7edb13e9c0bf',
    messagingSenderId: '16607490862',
    projectId: 'alaguide-app',
    storageBucket: 'alaguide-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqpA_uZbnpaBVGoIHDsUb3kO6CEoDcme8',
    appId: '1:16607490862:ios:1d2cb2f030b68c27e9c0bf',
    messagingSenderId: '16607490862',
    projectId: 'alaguide-app',
    storageBucket: 'alaguide-app.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqpA_uZbnpaBVGoIHDsUb3kO6CEoDcme8',
    appId: '1:16607490862:ios:1d2cb2f030b68c27e9c0bf',
    messagingSenderId: '16607490862',
    projectId: 'alaguide-app',
    storageBucket: 'alaguide-app.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJIHOR85lIhIADCOYU_gCFtF1p0N_QUPo',
    appId: '1:16607490862:web:7324b42b841e233ae9c0bf',
    messagingSenderId: '16607490862',
    projectId: 'alaguide-app',
    authDomain: 'alaguide-app.firebaseapp.com',
    storageBucket: 'alaguide-app.appspot.com',
  );
}
