# Generated by Django 5.0.4 on 2024-05-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'MapData',
                'managed': False,
            },
        ),
    ]
