# Generated by Django 5.0.4 on 2024-05-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mapdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
    ]
