# Generated by Django 5.0.4 on 2024-05-01 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiobook',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='landmark',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='landmarktag',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='likerating',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='socialprovider',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userreview',
            options={'managed': True},
        ),
    ]
