# Generated by Django 5.0.4 on 2024-05-01 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_audiobook_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='landmark',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.landmark'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.country'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.city'),
        ),
        migrations.AddField(
            model_name='landmarktag',
            name='landmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.landmark'),
        ),
        migrations.AddField(
            model_name='landmarktag',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tag'),
        ),
        migrations.AddField(
            model_name='likerating',
            name='landmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.landmark'),
        ),
        migrations.AddField(
            model_name='likerating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AddField(
            model_name='socialprovider',
            name='landmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.landmark'),
        ),
        migrations.AddField(
            model_name='socialprovider',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AddField(
            model_name='userreview',
            name='landmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.landmark'),
        ),
        migrations.AddField(
            model_name='userreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AlterUniqueTogether(
            name='landmarktag',
            unique_together={('landmark', 'tag')},
        ),
    ]
