# Generated by Django 5.0.4 on 2024-05-01 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_audiobook_landmark_city_country_landmark_category_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
    ]
