# Generated by Django 5.0.4 on 2024-05-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
    ]
