# Generated by Django 5.0.4 on 2024-05-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landmark',
            options={'managed': False},
        ),
    ]
