# Generated by Django 5.0.4 on 2024-05-01 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_landmark_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='landmark',
            options={'managed': True},
        ),
    ]
