# Generated by Django 5.0.4 on 2024-05-01 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_category_options_alter_landmark_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapdata',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='category',
            table='NewLandmarksCategory',
        ),
    ]
