# Generated by Django 5.0.4 on 2024-05-01 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_mapdata_options_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='LandmarksCategory',
        ),
    ]
