# Generated by Django 5.0.4 on 2024-05-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_category_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiobook',
            old_name='landmark',
            new_name='landmark_num',
        ),
    ]
