# Generated by Django 5.0.4 on 2024-05-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_landmark_audiobook_landmark_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landmark',
            options={'managed': False},
        ),
    ]
