# Generated by Django 5.0.4 on 2024-05-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_landmark_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiobook',
            old_name='landmark_num',
            new_name='landmark_id',
        ),
    ]
