---
name: Test

on:
  push:
    branches:
      - main
      - server_deployment

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.3

      - name: Create virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install mysql-client -y
      
      - name: Set up test database
        run: |
          mysql -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -h 185.22.64.41 -S /var/run/mysqld/mysqld.sock -e "CREATE DATABASE IF NOT EXISTS test_alaguide_db"

      - name: Run tests
        run: |
          python manage.py test
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'

      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: npm run build

      - name: Install Nginx
        run: sudo apt-get update && sudo apt-get install nginx -y

      - name: Configure Nginx
        run: |
          sudo cp /etc/nginx/nginx.conf  
          sudo systemctl restart nginx
      
      - name: Install PM2
        run: npm install pm2@latest -g

      - name: Start with PM2
        run: pm2 start backend/ecosystem.config.json
